extends SceneTree
const LocalResources = preload("res://scripts/resource_container.gd")
const Resources = preload("res://scripts/resource_type.gd")
const Buildings = preload("res://scripts/building_type.gd")
const Profession = preload("res://scripts/resident_profession.gd")
const Activity = preload("res://scripts/resident_activity.gd")
const FOOD = Resources.Type.FOOD
var failures := 0
func _initialize() -> void:
	call_deferred("_run")
func check(condition: bool, message: String) -> void:
	if not condition:
		failures += 1
		push_error(message)
func _run() -> void:
	var source = LocalResources.new(&"source")
	var destination = LocalResources.new(&"destination")
	check(not source.add(FOOD, 1), "Unconfigured capacity is zero")
	source.set_capacity(FOOD, 20)
	destination.set_capacity(FOOD, 5)
	source.add(FOOD, 5)
	destination.add(FOOD, 3)
	check(source.reserve_out(FOOD, 2) and source.get_available_amount(FOOD) == 3 and source.get_amount(FOOD) == 5, "Outgoing reserve retains physical stock")
	check(not source.reserve_out(FOOD, 4) and not source.try_take(FOOD, 4), "Second task and ordinary consumer cannot steal reserved stock")
	check(destination.reserve_in(FOOD, 2) and destination.get_free_capacity(FOOD) == 2 and destination.get_available_free_capacity(FOOD) == 0, "Incoming reserve retains physical free space")
	check(not destination.reserve_in(FOOD, 1) and not destination.add(FOOD, 1), "Second task and ordinary addition cannot fill promised space")
	check(not destination.set_capacity(FOOD, 4), "Capacity cannot shrink below promised space")
	check(source.take_reserved(FOOD, 2) and source.get_amount(FOOD) == 3 and source.get_reserved_out(FOOD) == 0, "Reserved withdrawal changes stock exactly once")
	check(not source.take_reserved(FOOD, 2), "Completed reservation cannot be consumed twice")
	check(destination.get_amount(FOOD) == 3, "Withdrawal does not teleport resource to destination")
	check(destination.add_reserved(FOOD, 2) and destination.get_amount(FOOD) == 5 and destination.get_reserved_in(FOOD) == 0, "Reserved delivery fills promised capacity exactly once")
	check(not destination.add_reserved(FOOD, 2), "Completed incoming reserve cannot be used twice")
	check(source.reserve_out(FOOD, 2) and source.release_out(FOOD, 1) and source.get_reserved_out(FOOD) == 1, "Partial outgoing release")
	check(not source.release_out(FOOD, 2) and source.release_out(FOOD, 1), "Over-release rejected without changing reservation")
	destination.try_take(FOOD, 2)
	destination.reserve_in(FOOD, 2)
	check(destination.release_in(FOOD, 1) and not destination.release_in(FOOD, 2) and destination.release_in(FOOD, 1), "Incoming release protects counts")
	for amount in [0, -1]:
		check(not source.reserve_out(FOOD, amount) and not source.release_out(FOOD, amount) and not source.take_reserved(FOOD, amount), "Invalid outgoing operations rejected")
		check(not destination.reserve_in(FOOD, amount) and not destination.release_in(FOOD, amount) and not destination.add_reserved(FOOD, amount), "Invalid incoming operations rejected")
	check(not destination.add(FOOD, 3) and destination.get_amount(FOOD) == 3, "Overcapacity addition is atomic")
	var scene = load("res://scenes/main.tscn").instantiate()
	root.add_child(scene)
	preload("res://tests/resident_test_setup.gd").isolate_first(scene)
	scene.game_time.set_process(false)
	scene.resident_runtimes[0].view.set_process(false)
	var warehouse = scene.warehouse_data
	var kitchen = scene.kitchen_data
	check(warehouse.type == Buildings.Type.STORAGE and warehouse.id == &"warehouse_01" and warehouse.display_name == "Склад", "Warehouse building data")
	check(warehouse.resources.get_amount(FOOD) == 10 and warehouse.resources.get_capacity(FOOD) == 20, "Warehouse starts 10 of 20")
	check(kitchen.resources.get_amount(FOOD) == 0 and kitchen.resources.get_capacity(FOOD) == 5, "Kitchen starts empty with capacity 5")
	check(scene.warehouse_food_label.text == "Еда на складе: 10/20" and scene.food_label.text == "Еда в кухне: 0/5", "UI reads separate stock")
	var view = scene.get_node("World/Warehouse")
	check(view.building_data == warehouse and scene.world_locations.get_location(warehouse.id).display_name == "Склад", "Warehouse view and distinct place registered")
	check(view.is_visible_in_tree() and view.get_node("Caption").text == "Склад", "Warehouse placeholder visible and labelled")
	view.position += Vector2(10, 0)
	check(scene.world_locations.get_position(warehouse.id) == view.global_position, "Warehouse uses existing position mapping")
	check(scene.residents[0].profession == Profession.Type.PORTER, "Stepan assigned PORTER")
	scene.resident_selection.select(scene.residents[0])
	var card = scene.get_node("HUD/ResidentCard")
	card._refresh()
	check(card.profession_label.text == "Профессия: Носильщик", "Card translates assigned profession")
	scene.residents[0].hunger = 75
	scene.resident_runtimes[0].view._process(20.0)
	scene.game_time.advance(5.0)
	check(scene.residents[0].activity == Activity.Type.IDLE and scene.residents[0].hunger == 75 and warehouse.resources.get_amount(FOOD) == 10, "Empty kitchen cannot eat warehouse stock; no logistics behavior")
	kitchen.resources.add(FOOD, 1)
	check(scene.food_label.text == "Еда в кухне: 1/5" and scene.warehouse_food_label.text == "Еда на складе: 10/20", "Independent UI updates")
	view.free()
	check(warehouse.resources.get_amount(FOOD) == 10, "Warehouse data survives view removal")
	scene.free()
	print("Reservation checks: ", "PASS" if failures == 0 else "FAIL (%d)" % failures)
	quit(0 if failures == 0 else 1)
