extends RefCounted
## Prototype balance values; no editor settings framework.
const UTILITY_CANDIDATE_RATIO := 0.75
const UTILITY_RANDOM_EXPONENT := 2.0
const SLEEP_SOCIAL_GROWTH_MULTIPLIER := 0.2
const SLEEP_LEISURE_GROWTH_MULTIPLIER := 0.2
const WORK_PRIORITY := 7000
const NEED_ACTION_THRESHOLD := 1000
const IMPORT_MULTIPLIER := 1.1
const EXPORT_MULTIPLIER := 1.0
const DEFAULT_BUILDING_LOGISTICS_WEIGHT := 100
const GATHERER_WORK_MINUTES_PER_FOOD := 30

const HUNGER_BASE_WEIGHT := 100
const FATIGUE_BASE_WEIGHT := 100
const SOCIAL_BASE_WEIGHT := 80
const LEISURE_BASE_WEIGHT := 75
const KITCHEN_FOOD_CAPACITY := 20
const EAT_MIN_HUNGER := 30
const EAT_MAX_UTILITY := 10000
const EAT_UTILITY_EXPONENT := 2.0
const WANDER_PRIORITY := 500
const WANDER_RADIUS := 100.0
const WANDER_STAY_MINUTES := 10
const CONVERSATION_POSITION_RADIUS := 64.0
const SOCIAL_GROWTH_DIVISOR := 5
const LEISURE_GROWTH_DIVISOR := 5
const RELAX_DURATION_MINUTES := 30
const WORK_CYCLE_MINUTES := 60
const MIN_CONVERSATION_MINUTES := 15
const MAX_CONVERSATION_MINUTES := 60
const CONVERSATION_RECHECK_MINUTES := 5
const CONVERSATION_EXIT_CHANCE := 0.2
