extends RefCounted
## Prototype balance values; no editor settings framework.
const ASSIGNMENT_BONUS := 3000
const UTILITY_CANDIDATE_RATIO := 0.75
const UTILITY_RANDOM_EXPONENT := 2.0
const SLEEP_SOCIAL_GROWTH_MULTIPLIER := 0.2
const SLEEP_LEISURE_GROWTH_MULTIPLIER := 0.2
const WORK_PRIORITY := 7000
const NEED_ACTION_THRESHOLD := 1000
const IMPORT_MULTIPLIER := 1.1
const EXPORT_MULTIPLIER := 1.0
const DEFAULT_BUILDING_LOGISTICS_WEIGHT := 100
const GATHERER_WORK_MINUTES_PER_FOOD := 30

const HUNGER_BASE_WEIGHT := 100
const FATIGUE_BASE_WEIGHT := 100
const SOCIAL_BASE_WEIGHT := 80
const LEISURE_BASE_WEIGHT := 75
const KITCHEN_FOOD_CAPACITY := 20
const EAT_MIN_HUNGER := 30
const EAT_MAX_UTILITY := 10000
const EAT_UTILITY_EXPONENT := 2.0
const WANDER_PRIORITY := 500
const WANDER_RADIUS := 100.0
const WANDER_STAY_MINUTES := 10
const CONVERSATION_POSITION_RADIUS := 64.0
const SOCIAL_GROWTH_DIVISOR := 5
const LEISURE_GROWTH_DIVISOR := 5
const RELAX_DURATION_MINUTES := 30
const WORK_CYCLE_MINUTES := 60
const MIN_CONVERSATION_MINUTES := 15
const MAX_CONVERSATION_MINUTES := 60
const CONVERSATION_RECHECK_MINUTES := 5
const CONVERSATION_EXIT_CHANCE := 0.2

# Construction site score is separate from WORK category utility.
const BUILDER_WORK_CYCLE_MINUTES = 60
const BUILDER_MATERIAL_PROGRESS_MAX = 2000.0
const BUILDER_CONSTRUCTION_PROGRESS_MAX = 2000.0
const BUILDER_ACTIVE_WORKER_BONUS = 1000.0
const BUILDER_DISTANCE_SCALE = 300.0
const BUILDER_DISTANCE_WEIGHT = 1000.0

const PORTER_DISTANCE_SCALE = 600.0
const PORTER_DISTANCE_WEIGHT = 1000.0

const HOUSE_RESIDENT_CAPACITY = 4 # Temporary prototype housing balance.

const HOME_SLEEP_QUALITY = 1.0
const OUTDOOR_SLEEP_QUALITY = 0.6

# Temporary progression; accumulated XP is retained if the curve changes later.
const SKILL_XP_PER_LEVEL = 10
const MAX_SKILL_LEVEL = 10

# First behavior modifier source: permanent traits. Base constants stay unchanged.
const SOCIABLE_SOCIAL_UTILITY_MULTIPLIER = 1.25
const INTROVERTED_SOCIAL_UTILITY_MULTIPLIER = 0.75
const INDUSTRIOUS_WORK_UTILITY_MULTIPLIER = 1.10
const LAZY_WORK_UTILITY_MULTIPLIER = 0.90
const GLUTTON_EAT_UTILITY_MULTIPLIER = 1.20
const GLUTTON_EAT_THRESHOLD_MODIFIER = -10
const RESTLESS_MOVEMENT_SPEED_MULTIPLIER = 1.10
const FOOLISH_UTILITY_CANDIDATE_RATIO = 0.55
const FOOLISH_UTILITY_RANDOM_EXPONENT = 1.50

# Directed relationship foundation; neutral reads do not allocate records.
const OPINION_MIN = -100
const OPINION_MAX = 100
const OPINION_NEUTRAL = 0
